require "spec/rake/spectask"

task :default => :spec
task :spec => ["spec:protocol", "spec:system"]

namespace :spec do
  Spec::Rake::SpecTask.new(:protocol) do |t|
    t.spec_opts = %w(-fs -c)
    t.spec_files = FileList["spec/protocol/**/*_spec.rb"]
  end

  Spec::Rake::SpecTask.new(:system) do |t|
    t.spec_opts = %w(-fs -c)
    t.spec_files = FileList["spec/system/**/*_spec.rb"]
  end
end