embed_assets: on
package_assets: on

stylesheets:
  ie:
    - public/stylesheets/ie.css
  print:
    - public/stylesheets/print.css 
  screen:
    - public/stylesheets/screen.css 
  site:
    - public/stylesheets/root/screen.css
  site_ie7:
    - public/stylesheets/root/ie_7.css
  site_ie8:
    - public/stylesheets/root/ie_8.css
