embed_assets: on
package_assets: always

stylesheets:
  ie:
    - public/stylesheets/ie.css
  print:
    - public/stylesheets/print.css 
  screen:
    - public/stylesheets/screen.css 
  site:
    - public/stylesheets/root/screen.css
