#!/usr/bin/env bash
echo "Starting all services ..."
echo "Don't you touch anything until you see 5 new tabs in your console."
gnome-terminal \
  --tab -e "bundle exec script/rabbitmq" -t 'RabbitMQ' \
  --tab -e "bundle exec thin start" -t 'Thin' \
  --tab -e "bundle exec script/orbited" -t "Orbited" &
 
sleep 5

gnome-terminal \
  --tab -e "bundle exec script/talker channel -d" -t "Talker Channel"\
  --tab -e "bundle exec script/talker presence -d" -t "Talker Presence" \
  --tab -e "bundle exec script/talker logger -d" -t "Talker Logger"
