#!/usr/bin/env bash
echo "Starting all services ..."
echo "Don't you touch anything until you see 5 new tabs in your console."
gnome-terminal \
  --tab -e "script/rabbitmq" -t 'RabbitMQ' \
  --tab -e "thin start" -t 'Thin' \
  --tab -e "script/orbited" -t "Orbited" &
 
sleep 5

gnome-terminal \
  --tab -e "script/talker channel" -t "Talker Channel"\
  --tab -e "script/talker presence" -t "Talker Presence" \
  --tab -e "script/talker logger" -t "Talker Logger"
