#!/usr/bin/env bash
echo "Starting all services ..."
echo "Don't you touch anything until you see 3 new tabs in your console."
thin start -d
echo "  thin started as a daemon (stop with 'thin stop')"
script/tab script/orbited
echo "  orbited started in a tab"
script/tab script/rabbitmq
echo "  rabbitmq started in a tab"
script/tab script/talker
echo "  talker started in a tab"
script/tab script/logger
echo "  talker-logger started in a tab"
open http://standoutjobs-development.com:3000/